name: Deploy to AWS Lambda
on:
  push:
    branches:
      - dev
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Prepare Serverless config
      run: cp serverless.yml.${{ github.ref == 'refs/heads/master' && 'master' || 'dev' }} serverless.yml
    - name: Deploy
      run: npx serverless deploy --stage $STAGE
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        STAGE: ${{ github.ref == 'refs/heads/master' && 'master' || 'dev' }}
